services:
  whatomate-api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: whatomate-api
    ports:
      - "5701:8080"
    environment:
      - WHATOMATE_APP_NAME=Whatomate
      - WHATOMATE_APP_ENVIRONMENT=production
      - WHATOMATE_APP_DEBUG=false
      - WHATOMATE_SERVER_HOST=0.0.0.0
      - WHATOMATE_SERVER_PORT=8080
      - WHATOMATE_DATABASE_HOST=whatomate-db
      - WHATOMATE_DATABASE_PORT=5432
      - WHATOMATE_DATABASE_USER=whatomate
      - WHATOMATE_DATABASE_PASSWORD=sswhatomate123
      - WHATOMATE_DATABASE_NAME=whatomate
      - WHATOMATE_DATABASE_SSL_MODE=disable
      - WHATOMATE_REDIS_HOST=whatomate-redis
      - WHATOMATE_REDIS_PORT=6379
      - WHATOMATE_JWT_SECRET=${JWT_SECRET:-sswhatomate123}
      - WHATOMATE_JWT_ACCESS_EXPIRY_MINS=480
      - WHATOMATE_WHATSAPP_WEBHOOK_VERIFY_TOKEN=${WEBHOOK_VERIFY_TOKEN:-SzTN4JFPwbf7}
    depends_on:
      whatomate-db:
        condition: service_healthy
      whatomate-redis:
        condition: service_healthy
    volumes:
      - whatomate_uploads:/app/uploads
    restart: unless-stopped

  whatomate-worker:
    build:
      context: ..
      dockerfile: docker/Dockerfile.worker
    container_name: whatomate-worker
    environment:
      - WHATOMATE_APP_NAME=Whatomate
      - WHATOMATE_APP_ENVIRONMENT=production
      - WHATOMATE_APP_DEBUG=false
      - WHATOMATE_DATABASE_HOST=whatomate-db
      - WHATOMATE_DATABASE_PORT=5432
      - WHATOMATE_DATABASE_USER=whatomate
      - WHATOMATE_DATABASE_PASSWORD=sswhatomate123
      - WHATOMATE_DATABASE_NAME=whatomate
      - WHATOMATE_DATABASE_SSL_MODE=disable
      - WHATOMATE_REDIS_HOST=whatomate-redis
      - WHATOMATE_REDIS_PORT=6379
    depends_on:
      whatomate-db:
        condition: service_healthy
      whatomate-redis:
        condition: service_healthy
    restart: unless-stopped

  whatomate-frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: whatomate-frontend
    ports:
      - "5702:80"
    depends_on:
      - whatomate-api
    restart: unless-stopped

  whatomate-db:
    image: postgres:15-alpine
    container_name: whatomate-db
    environment:
      - POSTGRES_USER=whatomate
      - POSTGRES_PASSWORD=whatomate123
      - POSTGRES_DB=whatomate
    volumes:
      - whatomate_postgres_data:/var/lib/postgresql/data
    ports:
      - "5703:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U whatomate"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  whatomate-redis:
    image: redis:7-alpine
    container_name: whatomate-redis
    command: redis-server --appendonly yes
    volumes:
      - whatomate_redis_data:/data
    ports:
      - "5704:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  whatomate_postgres_data:
  whatomate_redis_data:
  whatomate_uploads:
